on:
    workflow_call:
      inputs:
        BUILD_TIME:
            required: true
            type: string
        BUILD_COMMIT:
            required: true
            type: string
        BUILD_COMMIT_TS:
            required: true
            type: string
        BUILD_VERSION:
            required: true
            type: string
        debian_release:
            required: true
            type: string
jobs:
    back:
        runs-on: ubuntu-latest
        container:
          image: golang:1.19-${{inputs.debian_release}}
        steps:
        - uses: actions/checkout@v4
          with:
            repository: VKCOM/statshouse
            ref: ${{inputs.BUILD_COMMIT}}
            fetch-depth: 0
        - uses: actions/download-artifact@master
          with:
            name: statshouse-${{inputs.BUILD_VERSION}}-ui
        - run: |
            BUILD_TIME=${{inputs.BUILD_TIME}}
            BUILD_COMMIT=${{inputs.BUILD_COMMIT}}
            BUILD_COMMIT_TS=${{inputs.BUILD_COMMIT_TS}}
            BUILD_MACHINE=$(uname -n -m -r -s)
            BUILD_VERSION=${{inputs.BUILD_VERSION}}
            cp -r statshouse-ui/build cmd/statshouse-api/
            make build-sh build-sh-metadata build-sh-api build-sh-grafana
        - uses: actions/upload-artifact@v3
          with:
            name: statshouse-${{inputs.BUILD_VERSION}}-${{inputs.debian_release}}_amd64-bin
            path: target
    deb:
        needs: [back]
        runs-on: ubuntu-latest
        container:
          image: debian:${{inputs.debian_release}}
        steps:
        - run: |
            apt-get update
            DEBIAN_FRONTEND=noninteractive apt-get install -y devscripts build-essential dh-exec
            rm -rf /var/lib/apt/lists/*
        - uses: actions/checkout@v4
          with:
            repository: VKCOM/statshouse
            ref: ${{inputs.BUILD_COMMIT}}
            fetch-depth: 0
        - uses: actions/download-artifact@master
          with:
            name: statshouse-${{inputs.BUILD_VERSION}}-${{inputs.debian_release}}_amd64-bin
            path: target
        - uses: actions/download-artifact@master
          with:
            name: statshouse-${{inputs.BUILD_VERSION}}-ui
        - working-directory: build
          run: |
            rm -f changelog
            VERSION=1:${{inputs.BUILD_VERSION}}-${{inputs.debian_release}}
            dch --create --distribution stable --package statshouse --newversion "$VERSION" "up to version $VERSION"
            debuild --no-lintian -us -uc -b
        - run: |
            mkdir ${{inputs.debian_release}}
            mv *.deb ${{inputs.debian_release}}
        - uses: actions/upload-artifact@v3
          with:
            name: statshouse-${{inputs.BUILD_VERSION}}_amd64-deb
            path: |
              ${{inputs.debian_release}}/statshouse_*
              ${{inputs.debian_release}}/statshouse-api_*
              ${{inputs.debian_release}}/statshouse-metadata_*
              .dummy_preserves_directory_structure
